/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/About.vue')['default']
    CompleteNode: typeof import('./src/components/CompleteNode.vue')['default']
    ListResults: typeof import('./src/components/ListResults.vue')['default']
    ListResultsDashboard: typeof import('./src/components/ListResultsDashboard.vue')['default']
    ListWorkflows: typeof import('./src/components/ListWorkflows.vue')['default']
    ListWorkflowsDashboard: typeof import('./src/components/ListWorkflowsDashboard.vue')['default']
    LoadingNode: typeof import('./src/components/LoadingNode.vue')['default']
    Logout: typeof import('./src/components/Logout.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MenuLogined: typeof import('./src/components/MenuLogined.vue')['default']
    OKNode: typeof import('./src/components/OKNode.vue')['default']
    OpenResultPreview: typeof import('./src/components/OpenResultPreview.vue')['default']
    OpenWorkflow: typeof import('./src/components/OpenWorkflow.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ToLogin: typeof import('./src/components/ToLogin.vue')['default']
    ToRegister: typeof import('./src/components/ToRegister.vue')['default']
    UploadFiles: typeof import('./src/components/UploadFiles.vue')['default']
    UserFiles: typeof import('./src/components/UserFiles.vue')['default']
    WaitingNode: typeof import('./src/components/WaitingNode.vue')['default']
    WorkFlow: typeof import('./src/components/WorkFlow.vue')['default']
  }
}
